### ISSUE TITLE
Too many panics?

### ISSUE THREAD

**Issue by di-bon** [The-Null-Pointer-Patrol/null-pointer-drone#35]
I think that some panics can be avoided, I'll add them later in this issue

**Comment by di-bon** [comment]
Here is the list of the panics I think can be safely removed:
- panic when trying to remove a nonexistent channel from `self.packet_send`
- panic when receiving an `Err` from `recv(self.packet_recv)` and `self.state == State::Working:` not sure about this, but shouldn't it be removed? For instance, if a group decides to change the topology by first removing all the channels between the drones and then adding them back, shouldn't our drone keep running? I guess that this may create issues similar to the one we were talking about in #32
- panic when `FloodRequest` has no elements in `path_trace`: since `FloodRequest` packets may be lost during the simulation, wouldn't be better to just drop a malformed packet of this type instead of panicking?

**Comment by marcoff181** [comment]
> panic when trying to remove a nonexistent channel from self.packet_send

I understand the worry with this, but I would still like a way to tell the SimulationController that that connection wasn't there to begin with, because it means that the simulation controller information about the network is incorrect. I can't think of any other way to notify a generic SimulationController of any group of the fact that their message was incorrect.

> panic when receiving an Err from recv(self.packet_recv)

This panic should be kept, because if a group removes all the channel between the drones it still has to keep a copy of the sender in the sim controller, and in that case we don't get an Err.

In the other case, where all senders have been dropped, then the group has no way to add senders to that drone anymore, and it becomes an unrecoverable situation, which leads to a well deserved panic : )

> panic when FloodRequest has no elements in path_trace

I dont't think packets being lost would ever lead to an empty path trace with functioning drones in the network. If you get an empty path trace it means that the drone who sent it to you has some errors in its flooding logic. If I were a person that bought our drone, and is testing it with other drones, I would prefer that it tells me there is something wrong in the network by panicking, otherwise I either don't find the issue or find it thanks to something else.

My reasoning basically is: Is there any reason I would want my simulation to go on even when there is a faulty drone that creates incorrect flooding packets? I think not, but it's just my personal opinion

### What should we do with all these panics?
Personally, I think we should have good documentation in the readme for all the panics we throw, then when (if) we have people that buy our drone they can tell us if they would prefer not to have certain panics and we can discuss those.

**Comment by marcoff181** [comment]
Although in the 2nd panic you presented it would be good to have a more descriptive panic that explains that all senders have been dropped and that means there is no way to send packets to that drone anymore

**Comment by saussice9** [comment]
Good idea to add that in readme but the panic in the `set_pdr` fonction is realy necessary should we just ignore it and logging it? We just keep the former value
